### ISSUE TITLE
Ревью по проекту

### ISSUE THREAD

**Issue by DramatikMan** [HSchoolboyEr/WhatThisFuncDo#1]
- [x] [Бинарные артефакты](https://github.com/HSchoolboyEr/WhatThisFuncDo/tree/main/models_pickle), изображения и [таблицы](https://github.com/HSchoolboyEr/WhatThisFuncDo/tree/main/data/for_linear_models) хранить лучше в файловых хранилищах и получать их содержимое в рантайме через запросы
- [x] В [requirements.txt](https://github.com/HSchoolboyEr/WhatThisFuncDo/blob/main/tools/TG_bot/requirements.txt) не указаны версии зависимостей. Это нужно для стабильной воспроизводимости логики. В идеале лучше использовать менеджер среды, поддерживающей lock зависимостей по хэшу дистрибутива (например [Poetry](https://python-poetry.org/) или [PDM](https://pdm.fming.dev/latest/))
- [x] Для приложений с Python рантаймом не следует использовать [базовый образ](https://github.com/HSchoolboyEr/WhatThisFuncDo/blob/main/tools/TG_bot/Dockerfile#L2) `alpine`. Дистрибутивы `alpine` используют `musl` вместо `glibc`, что приводит к сборке огромных библиотечных файлов Python зависимостей, и, как следствие, к огромному размеру образа. Лучше использовать [специальные базовые образы](https://hub.docker.com/_/python), где Python нужной версии уже изначально установлен. Рекомендую slim образы

**Comment by HSchoolboyEr** [comment]
Спасибо, все по делу!

Первый chek-box закрыл, так как знаю об этом (потому и просил смотреть только часть с ботом в комментарии). Но пока нет возможности исправить. Потом, когда найду время, доделаю все с DVC и mlflow, датасет перенесу на внешнее хранилище.
